Packages = write-good, proselint, neighbor, alex, Google

MinAlertLevel = suggestion

# List of styles to load.
[*.{md,txt,rst,adoc}]
BasedOnStyles = Vale, s2e, write-good, proselint, neighbor, alex
# Style.Rule = {YES, NO, suggestion, warning, error} to
# enable/disable a rule or change its level.
Vale.Spelling = NO
Vale.Repetition = NO # Using write-good-Illusions
# I like cursing
proselint.Cursing = NO
alex.ProfanityLikely = NO
alex.ProfanityMaybe = NO
neighbor.AllCapsProse = NO
Google.ExcessiveClaims = YES
Google.Jargon = YES
Google.OxfordComma = YES
Google.Spelling = YES
Google.Anthropomorphism = YES
proselint.Annotations = NO

[*.{org}]
BasedOnStyles = Vale, s2e, write-good, proselint, neighbor, alex
Vale.Spelling = NO
Vale.Repetition = NO # Using write-good-Illusions
proselint.Cursing = NO
alex.ProfanityLikely = NO
alex.ProfanityMaybe = NO
neighbor.AllCapsProse = NO
Google.ExcessiveClaims = YES
Google.Jargon = YES
Google.OxfordComma = YES
Google.Spelling = YES
Google.Anthropomorphism = YES
proselint.Annotations = NO